package org.example.Entidad;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="requests")
public class RequestData {

    private String uniqueId;
    private String studentId;
    private String fullName;
    private String emailAddress;
    private String labName;
    private String reserveDate;
    private String reserveHour;

    public RequestData() {
    }

    public RequestData(String studentId, String fullName, String emailAddress, String labName, String reserveDate, String reserveHour) {
        this.studentId = studentId;
        this.fullName = fullName;
        this.emailAddress = emailAddress;
        this.labName = labName;
        this.reserveDate = reserveDate;
        this.reserveHour = reserveHour;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getUniqueId() {
        return uniqueId;
    }
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    @DynamoDBAttribute(attributeName="matricula")
    public String getStudentId() {
        return studentId;
    }
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    @DynamoDBAttribute(attributeName="nombre")
    public String getFullName() {
        return fullName;
    }
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @DynamoDBAttribute(attributeName="correo")
    public String getEmailAddress() {
        return emailAddress;
    }
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    @DynamoDBAttribute(attributeName = "laboratorio")
    public String getLabName() {
        return labName;
    }
    public void setLabName(String labName) {
        this.labName = labName;
    }

    @DynamoDBAttribute(attributeName="fecha")
    public String getReserveDate() {
        return reserveDate;
    }
    public void setReserveDate(String reserveDate) {
        this.reserveDate = reserveDate;
    }

    @DynamoDBAttribute(attributeName="hora")
    public String getReserveHour() {
        return reserveHour;
    }
    public void setReserveHour(String reserveHour) {
        this.reserveHour = reserveHour;
    }

    @Override
    public String toString() {
        return "RequestData{" +
                "uniqueId='" + uniqueId + '\'' +
                ", studentId='" + studentId + '\'' +
                ", fullName='" + fullName + '\'' +
                ", emailAddress='" + emailAddress + '\'' +
                ", labName='" + labName + '\'' +
                ", reserveDate='" + reserveDate + '\'' +
                ", reserveHour='" + reserveHour + '\'' +
                '}';
    }
}
